sudo: false
language: python
python:
    - "3.7"

addons:
    apt:
        packages:
            - graphviz

install:
    - pip install --upgrade behave blinker coverage coveralls ipython ipywidgets nbformat networkx numpy Pillow pygraphviz
script:
    - coverage run --source graphcat -m behave
    - coverage report
after_script:
    - coveralls

notifications:
    webhooks:
        - https://graphcat.zulipchat.com/api/v1/external/travis?api_key=ZS0kyNb2Mg3Ycg5NiJkl28ZeeFaxhip0&stream=repo&topic=builds
