sudo: false
language: python
python:
    - "3.7"

addons:
    apt:
        packages:
            - graphviz

install:
    - pip install behave blinker coveralls ipython networkx pygraphviz
script:
    - coverage run --source graphcat -m behave
    - coverage report
after_script:
    - coveralls
